name: ci-mcp-sanity
permissions:
  contents: read
on:
  pull_request:
    paths:
      - 'packages/mcp/**'
      - 'packages/common/**' # Added common since it's a dependency
      - 'packages/db/**' # Added common since it's a dependency
      - '.github/workflows/ci-mcp-sanity.yml'
      - 'package.json'
      - 'yarn.lock'

jobs:
  build-and-test-mcp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Prepare testdatabase & build library packgaes
        run: yarn setup

      - name: run test database
        run: |
          yarn couchdb:start
          npx wait-on --timeout 5m http://localhost:5984

      - name: Verify databases
        run: curl http://admin:password@localhost:5984/_all_dbs

      - name: Build mcp package and examples
        run: |
          yarn workspace @vue-skuilder/mcp build
          yarn workspace @vue-skuilder/mcp build:examples

      - name: list resources
        run: |
          yarn workspace @vue-skuilder/mcp test:resources

      - name: list tools
        run: |
          yarn workspace @vue-skuilder/mcp test:tools

      - name: list prompts
        run: |
          yarn workspace @vue-skuilder/mcp test:prompts
