name: deploy-express
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for deploying Express API'
        required: true
        default: 'Manual trigger'
jobs:
  deploy-express:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was triggered by a ${{ github.event_name }} on commit ${{ github.SHA }}"
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Enable Corepack
        run: corepack enable

      - name: Configure SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Install dependencies
        run: yarn install

      - name: Build workspace dependencies
        run: |
          # Build common package if it exists
          if [ -d "./packages/common" ]; then
            echo "Building @vue-skuilder/common package..."
            cd ./packages/common
            yarn build
            cd ../..
          fi
          
          # Build db package if it exists
          if [ -d "./packages/db" ]; then
            echo "Building @vue-skuilder/db package..."
            cd ./packages/db
            yarn build
            cd ../..
          fi

      - name: Build Express API
        run: |
          cd ./packages/express
          yarn build

      - name: Deploy and run
        run: |

          # Create necessary directories
          ssh ${{ secrets.DO_USERNAME }}@eduquilt.com mkdir -p /home/skuilder/dist/express/${{github.sha}}
          ssh ${{ secrets.DO_USERNAME }}@eduquilt.com mkdir -p /home/skuilder/dist/express/${{github.sha}}/assets

          # Copy build artifacts and dependencies
          rsync -rl ./packages/express/dist/ ${{ secrets.DO_USERNAME }}@eduquilt.com:/home/skuilder/dist/express/${{github.sha}}
          rsync -rl ./packages/express/assets/ ${{ secrets.DO_USERNAME }}@eduquilt.com:/home/skuilder/dist/express/${{github.sha}}/assets
          rsync -rl ./packages/express/package.json ${{ secrets.DO_USERNAME }}@eduquilt.com:/home/skuilder/dist/express/${{github.sha}}
          
          # Handle workspace dependencies by copying them to the server
          if [ -d "./packages/common" ]; then
            echo "Copying @vue-skuilder/common package..."
            ssh ${{ secrets.DO_USERNAME }}@eduquilt.com mkdir -p /home/skuilder/dist/common/dist
            rsync -rl ./packages/common/dist/ ${{ secrets.DO_USERNAME }}@eduquilt.com:/home/skuilder/dist/common/dist
            rsync -rl ./packages/common/package.json ${{ secrets.DO_USERNAME }}@eduquilt.com:/home/skuilder/dist/common/
          fi
          
          if [ -d "./packages/db" ]; then
            echo "Copying @vue-skuilder/db package..."
            ssh ${{ secrets.DO_USERNAME }}@eduquilt.com mkdir -p /home/skuilder/dist/db/dist
            rsync -rl ./packages/db/dist/ ${{ secrets.DO_USERNAME }}@eduquilt.com:/home/skuilder/dist/db/dist
            rsync -rl ./packages/db/package.json ${{ secrets.DO_USERNAME }}@eduquilt.com:/home/skuilder/dist/db/
          fi
          
          # Replace workspace references with file paths
          TMP_PKG=$(cat ./packages/express/package.json | sed 's|"@vue-skuilder/common": "workspace:^"|"@vue-skuilder/common": "file:/home/skuilder/dist/common"|g' | sed 's|"@vue-skuilder/db": "workspace:^"|"@vue-skuilder/db": "file:/home/skuilder/dist/db"|g')
          echo "$TMP_PKG" > ./packages/express/temp-package.json
          rsync -rl ./packages/express/temp-package.json ${{ secrets.DO_USERNAME }}@eduquilt.com:/home/skuilder/dist/express/${{github.sha}}/package.json
          
          # Install dependencies on the server (using full path to yarn)
          echo "Installing dependencies for Express app..."
          ssh ${{ secrets.DO_USERNAME }}@eduquilt.com "cd /home/skuilder/dist/express/${{github.sha}} && source ~/.nvm/nvm.sh && yarn install --production"
          
          # Install dependencies for workspace packages
          if [ -d "./packages/common" ]; then
            echo "Installing dependencies for common package..."
            ssh ${{ secrets.DO_USERNAME }}@eduquilt.com "cd /home/skuilder/dist/common && source ~/.nvm/nvm.sh && yarn install --production"
          fi
          
          if [ -d "./packages/db" ]; then
            echo "Installing dependencies for db package..."
            ssh ${{ secrets.DO_USERNAME }}@eduquilt.com "cd /home/skuilder/dist/db && source ~/.nvm/nvm.sh && yarn install --production"
          fi

          # Update symlink to new version
          ssh ${{ secrets.DO_USERNAME }}@eduquilt.com ln -sfn /home/skuilder/dist/express/${{github.SHA}} /home/skuilder/api

          # Update environment variables
          ssh ${{ secrets.DO_USERNAME }}@eduquilt.com rm -f /home/skuilder/.env.development.local
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo VERSION=${{ github.SHA }} >> /home/skuilder/.env.development.local'
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo COUCHDB_ADMIN=${{ secrets.COUCHDB_ADMIN }} >> /home/skuilder/.env.development.local'
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo COUCHDB_PASSWORD=${{ secrets.COUCHDB_PASSWORD }} >> /home/skuilder/.env.development.local'
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo COUCHDB_PROTOCOL=${{ secrets.COUCHDB_PROTOCOL }} >> /home/skuilder/.env.development.local'
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo COUCHDB_SERVER=${{ secrets.COUCHDB_SERVER }} >> /home/skuilder/.env.development.local'

          # Restart service
          echo "Restarting Express service..."
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo ${{ secrets.DO_PASSWORD }} | sudo -S systemctl restart eqExpress'

          echo "Waiting for service to start..."
          sleep 10s
      - name: Verify deployment
        run: |
          echo "Verifying Express API deployment..."
          max_retries=3
          retry_count=0
          while [ $retry_count -lt $max_retries ]; do
            response=$(curl -sS https://eduquilt.com/express)
            if [[ $? -ne 0 ]]; then
              echo "Error: Failed to fetch https://eduquilt.com/express"
              retry_count=$((retry_count+1))
              if [ $retry_count -lt $max_retries ]; then
                echo "Retrying in 5 seconds... (Attempt $retry_count of $max_retries)"
                sleep 5
                continue
              else
                exit 1
              fi
            fi

            if echo "$response" | grep -q "${{ github.SHA }}"; then
              echo "Success. Current version found in production"
              
              # Log deployment success
              echo "✅ Express API deployed successfully with version ${{ github.SHA }}"
              echo "✅ Deployment triggered by: ${{ github.event.inputs.reason }}"
              echo "✅ Deployment timestamp: $(date -u)"
              
              exit 0
            else
              echo "Current version not found in production. Retrying..."
              retry_count=$((retry_count+1))
              if [ $retry_count -lt $max_retries ]; then
                echo "Retrying in 5 seconds... (Attempt $retry_count of $max_retries)"
                sleep 5
              else
                echo "Error! Max retries reached. Current version not reported by production."
                echo "Response received:"
                echo "$response"
                exit 1
              fi
            fi
          done
